/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import FormAutor.FormNoviAutor;
import FormAutor.FormPretragaAutora;
import FormMuzickaKompozicija.FormPretragaMuzickeKompozicije;
import controller.ClientController;
import domain.Autor;
import domain.MuzickaKompozicija;
import domain.MuzickiUrednik;
import domain.Uloga;
import domain.UlogaKompozicije;
import domain.Zanr;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.TableModelUloge;
import session.Session;

/**
 *
 * @author PC
 */
public class MainForm extends javax.swing.JFrame {

    MuzickiUrednik muzickiUrednik;
    ArrayList<Uloga> uloge;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        this.muzickiUrednik = Session.getInstance().getUlogovani();
        lblUlogovani.setText("Ulogovani muzicki urednik: " + muzickiUrednik);
        setTitle("Klijentska forma");
        popuniZanrove();
        popuniAutore();
        popuniUloge();
        tblUloge.setModel(new TableModelUloge());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUlogovani = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUloge = new javax.swing.JTable();
        btnDodaj = new javax.swing.JButton();
        btnObrisiUlogu = new javax.swing.JButton();
        cmbAutor = new javax.swing.JComboBox();
        cmbUloga = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtKomentar = new javax.swing.JTextArea();
        btnSacuvaj = new javax.swing.JButton();
        cmbZanr = new javax.swing.JComboBox();
        txtNazivKompozicije = new javax.swing.JTextField();
        txtGodinaNastanka = new javax.swing.JFormattedTextField();
        txtDuzinaTrajanja = new javax.swing.JFormattedTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        miNoviAutor = new javax.swing.JMenuItem();
        miPretragaAutora = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        miPretragaMuzickeKompozicije = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        miLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUlogovani.setText("Ulogovani");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos kompozicije"));

        jLabel1.setText("Zanr:");

        jLabel2.setText("Naziv kompozicije:");

        jLabel3.setText("Godina nastanka:");

        jLabel4.setText("Duzina trajanja (sekundi):");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos uloga kompozicije"));

        jLabel5.setText("Autor:");

        jLabel6.setText("Uloga:");

        jLabel7.setText("Komentar autora:");

        tblUloge.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUloge);

        btnDodaj.setText("Dodaj ulogu");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnObrisiUlogu.setText("Obrisi ulogu");
        btnObrisiUlogu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiUloguActionPerformed(evt);
            }
        });

        cmbAutor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbUloga.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtKomentar.setColumns(20);
        txtKomentar.setRows(5);
        jScrollPane2.setViewportView(txtKomentar);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(83, 83, 83)
                        .addComponent(cmbAutor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbUloga, 0, 286, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnObrisiUlogu, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnDodaj)
                    .addComponent(btnObrisiUlogu)
                    .addComponent(cmbAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbUloga, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSacuvaj.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnSacuvaj.setText("Sacuvaj kompoziciju");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        cmbZanr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtNazivKompozicije.setText("Kasno je");

        txtGodinaNastanka.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtGodinaNastanka.setText("2022");

        txtDuzinaTrajanja.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtDuzinaTrajanja.setText("206");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(49, 49, 49))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbZanr, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNazivKompozicije)
                            .addComponent(txtGodinaNastanka)
                            .addComponent(txtDuzinaTrajanja))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbZanr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNazivKompozicije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtGodinaNastanka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDuzinaTrajanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
        );

        jMenu6.setText("Autor");

        miNoviAutor.setText("Novi autor");
        miNoviAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNoviAutorActionPerformed(evt);
            }
        });
        jMenu6.add(miNoviAutor);

        miPretragaAutora.setText("Pretraga autora");
        miPretragaAutora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaAutoraActionPerformed(evt);
            }
        });
        jMenu6.add(miPretragaAutora);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Muzicka kompozicija");

        miPretragaMuzickeKompozicije.setText("Pretraga muzicke kompozicije");
        miPretragaMuzickeKompozicije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaMuzickeKompozicijeActionPerformed(evt);
            }
        });
        jMenu7.add(miPretragaMuzickeKompozicije);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Izloguj se");

        miLogout.setText("Izloguj se sa sistema");
        miLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoutActionPerformed(evt);
            }
        });
        jMenu8.add(miLogout);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblUlogovani))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUlogovani)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miNoviAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNoviAutorActionPerformed
        new FormNoviAutor(this, true).setVisible(true);
    }//GEN-LAST:event_miNoviAutorActionPerformed

    private void miPretragaAutoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaAutoraActionPerformed
        new FormPretragaAutora(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaAutoraActionPerformed

    private void miPretragaMuzickeKompozicijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaMuzickeKompozicijeActionPerformed
        new FormPretragaMuzickeKompozicije(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaMuzickeKompozicijeActionPerformed

    private void miLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoutActionPerformed

        int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da "
                + "izlogujete sa sistema?", "Konfirmacija", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.NO_OPTION) {
            return;
        }

        if (result == JOptionPane.YES_OPTION) {
            new LoginForma().setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_miLogoutActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed

        Autor a = (Autor) cmbAutor.getSelectedItem();
        Uloga u = (Uloga) cmbUloga.getSelectedItem();
        String komentar = txtKomentar.getText();

        if (txtKomentar.getText().isEmpty()) {
            komentar = "Bez komentara.";
        }

        TableModelUloge tm = (TableModelUloge) tblUloge.getModel();

        if (tm.postojiUloga(u, a)) {
            JOptionPane.showMessageDialog(this, "Vec ste uneli ovog autora za istu ulogu!");
            return;
        }

        UlogaKompozicije uk = new UlogaKompozicije(null, -1, komentar, u, a);

        tm.dodajUlogu(uk);

    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnObrisiUloguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiUloguActionPerformed

        int row = tblUloge.getSelectedRow();

        if (row >= 0) {
            TableModelUloge tm = (TableModelUloge) tblUloge.getModel();
            tm.obrisiUlogu(row);
        }

    }//GEN-LAST:event_btnObrisiUloguActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed

        try {

            if (txtNazivKompozicije.getText().isEmpty()
                    || txtDuzinaTrajanja.getText().isEmpty()
                    || txtGodinaNastanka.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Sva polja moraju biti popunjena!");
                return;
            }

            Zanr z = (Zanr) cmbZanr.getSelectedItem();
            String nazivKompozicije = txtNazivKompozicije.getText();
            int godinaNastanka = Integer.parseInt(txtGodinaNastanka.getText());
            int duzinaTrajanja = Integer.parseInt(txtDuzinaTrajanja.getText());

            TableModelUloge tm = (TableModelUloge) tblUloge.getModel();

            if (!tm.postojeSveUloge(uloge)) {
                JOptionPane.showMessageDialog(this, "Morate uneti sve 3 uloge!");
                return;
            }

            MuzickaKompozicija mk = new MuzickaKompozicija(null, nazivKompozicije, godinaNastanka,
                    duzinaTrajanja, z, muzickiUrednik, tm.getLista());

            ClientController.getInstance().addMuzickaKompozicija(mk);
            resetujFormu();
            JOptionPane.showMessageDialog(this, "Uspesno sacuvana muzicka kompozicija!");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnSacuvajActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnObrisiUlogu;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbAutor;
    private javax.swing.JComboBox cmbUloga;
    private javax.swing.JComboBox cmbZanr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblUlogovani;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenuItem miNoviAutor;
    private javax.swing.JMenuItem miPretragaAutora;
    private javax.swing.JMenuItem miPretragaMuzickeKompozicije;
    private javax.swing.JTable tblUloge;
    private javax.swing.JFormattedTextField txtDuzinaTrajanja;
    private javax.swing.JFormattedTextField txtGodinaNastanka;
    private javax.swing.JTextArea txtKomentar;
    private javax.swing.JTextField txtNazivKompozicije;
    // End of variables declaration//GEN-END:variables

    private void popuniZanrove() {
        try {
            ArrayList<Zanr> zanrovi = ClientController.getInstance().getAllZanr();

            cmbZanr.removeAllItems();

            for (Zanr zanr : zanrovi) {
                cmbZanr.addItem(zanr);
            }

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void popuniAutore() {
        try {
            ArrayList<Autor> autori = ClientController.getInstance().getAllAutor();

            cmbAutor.removeAllItems();

            for (Autor autor : autori) {
                cmbAutor.addItem(autor);
            }

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void popuniUloge() {
        try {
            uloge = ClientController.getInstance().getAllUloga();

            cmbUloga.removeAllItems();

            for (Uloga uloga : uloge) {
                cmbUloga.addItem(uloga);
            }

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void resetujFormu() {
        txtNazivKompozicije.setText("");
        txtGodinaNastanka.setText("");
        txtDuzinaTrajanja.setText("");
        TableModelUloge tm = (TableModelUloge) tblUloge.getModel();
        tm.getLista().clear();
        tm.fireTableDataChanged();
    }

}
